# netlify.toml - Main configuration file for Netlify

[build]
  publish = "."

# Specific redirects for HTML pages
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/gallery.html"
  status = 200

[[redirects]]
  from = "/order"
  to = "/order.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

# Fallback redirect - This is crucial for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

